---
- name: Check if Python is installed
  hosts: all
  tasks:
    - name: Check for Python 3.x
      command: python3 --version
      register: python3_version
      ignore_errors: yes

    - name: Check for Python 2.x
      command: python --version
      register: python2_version
      ignore_errors: yes

    - name: Display Python 3 version
      debug:
        msg: "Python 3 is installed: {{ python3_version.stdout }}"
      when: python3_version.rc == 0

    - name: Display Python 2 version
      debug:
        msg: "Python 2 is installed: {{ python2_version.stdout }}"
      when: python2_version.rc == 0

    - name: No Python installed
      fail:
        msg: "No Python installation found."
      when: python3_version.rc != 0 and python2_version.rc != 0
